spring:
  cloud:
    nacos:
    discovery:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: mms-backend-user-service
          uri: lb://mms-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: mms-backend-team-service
          uri: lb://mms-backend-team-service
          predicates:
            - Path=/api/team/**
        - id: mms-backend-department-service
          uri: lb://mms-backend-department-service
          predicates:
            - Path=/api/department/**
        - id: mms-backend-meeting-service
          uri: lb://mms-backend-meeting-service
          predicates:
            - Path=/api/meeting/**
        - id: mms-backend-meetingReserve-service
          uri: lb://mms-backend-meetingReserve-service
          predicates:
            - Path=/api/meeting_reserve/**
        - id: mms-backend-reserve-service
          uri: lb://mms-backend-reserve-service
          predicates:
            - Path=/api/reserve/**
  application:
    name: mms-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2